### ISSUE TITLE
multimodule: widgetset not included in Eclipse-generated war when using fetch mode

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/archetypes#112]
If you create a new multimodule application with 7.7.5 and set the widgetset mode to 'fetch', the Eclipse war generation won't include the widgetset. The multimodule does contain an add-on project by default (which would usually mean using 'local' mode), but if you delete that project and remove it from the parent pom.xml, you should be able to use fetch. I believe it was working correctly in 7.6.5.

Building the UI project with 'mvn package' works correctly, it includes the widgetset as expected. However, in Eclipse Neon, deploying the module to a local development server or exporting a .war leaves the widgetset out.

Steps to reproduce the issue: 
* Create a new project with Vaadin multimodule archetype:

mvn archetype:generate  \
  -DarchetypeGroupId=com.vaadin \
  -DarchetypeArtifactId=vaadin-archetype-application-multimodule \
  -DarchetypeVersion=7.7.5 \
  -DgroupId=com.widgetsetfailure \
  -DartifactId=widgetsetfailure \
  -Dversion=1.0-SNAPSHOT

* Remove add-on project:

cd widgetsetfailure
rm -r widgetsetfailure-addon
sed -i '/widgetsetfailure-addon/d' pom.xml

* Use widgetset fetching:

sed -i 's/<vaadin.widgetset.mode>local/<vaadin.widgetset.mode>fetch/' pom.xml

* Open the generated project in Eclipse Neon by File > Import > Existing Maven Projects.

* Export UI project .war or deploy to local server

Outcome: .war file doesn't contain widgetset
Expected: widgetset is included in  /WEB-INF/classes/VAADIN/widgetsets/

**Comment by mrts** [comment]
We had to revert back to `local` widgetset mode due to this error - too bad, the compile time win was significant.

**Comment by tsuoanttila** [comment]
@mrts The issue is part of eclipse-plugin, not the archetype project actually. And you should still be able to use the CDN mode, even though the fetch mode does not work. Related ticket in correct projcet: vaadin/eclipse-plugin#693

**Comment by mrts** [comment]
Thanks for the advice! However, we don't want to rely on the 3-rd party CDN in production.

**Comment by tsuoanttila** [comment]
We do recommend using the local compilation for production and CDN/fetch for development anyway. So at least when developing you can make things faster.

**Comment by mrts** [comment]
Interesting... do you have an example how to configure this somewhere?
