### ISSUE TITLE
Use V8 branch in Vaadin 8 related builds

### ISSUE THREAD

**Issue by pleku** [vaadin/archetypes#146]
Framework 8.7: (latest maintenance)
- [x] Release build
- [x] Snapshots build ?
- [x] Test build ?
Framework master (8.8)
- [x] Release build
- [x] Snapshots build ?
- [x] Test build ?

**Comment by ZheSun88** [comment]
Archetype has been used only Framework `release` build configurations neither in `snapshot` nor `test`. 

corresponding VCS root has been changed to use V8 instead of master.
