### ISSUE TITLE
Add release build for platform archetypes

### ISSUE THREAD

**Issue by pleku** [vaadin/archetypes#153]
Add a release build to bender that:
- releases a version of all the archetypes that matches the used platform version
- builds the archetype
- stages it
- ships it to to Maven central.

(Similarly as the FW8 archetype release builds in bender.)

The build should be setup in a way that it can be just run after there is a new platform release (the latest version, not LTS), so it either automatically updates to that (using a maven command), or then the new version is given as a parameter to the build and updated. This might need some changes to be applied to the code.

**Comment by ZheSun88** [comment]
release configuration:
https://bender.vaadin.com/project.html?projectId=Flow_Release_FlowArchetypesRelease&tab=projectOverview

13.0.2 release artifacts: https://repo.maven.apache.org/maven2/com/vaadin/vaadin-archetype-application/13.0.2/
