### ISSUE TITLE
Create a Spring Boot-based Maven archetype

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/archetypes#176]
Vaadin's [tech strategy](https://docs.google.com/document/d/174rhIJimwG1fZ7oLzEXqLIUG7A9CWkzXlcUMvT5WgAc) recommends and prioritizes the use of Spring Boot, yet the available Maven archetype generates a plain Java project. Thus, for consistency with the tech strategy, and in order to better address the needs of Spring Boot developers, consider providing a Maven archetype that generates a Spring Boot project (preferably in addition to the existing plain-Java one).

**Comment by tarekoraby** [comment]
@pleku how much extra manpower would be needed for the Flow team to take ownership of the archetype? or are there other constraints besides manpower? 

To my mind, having a Spring Boot-based archetype is a high-impact enhancement, so it would be a shame for it to fall between the cracks of our internal org. silos.

**Comment by Artur-** [comment]
If we want an archetype, we should generate it based on start.vaadin.com. This avoids maintenance and keeps the number of different/mismatching project setups to a minimum

**Comment by pleku** [comment]
@tarekoraby I think the ownership belongs to whomever looks after SVC based projects+templates and other starting points. That is not Flow team today and it can't be.

The Flow team has hands full with things that need deep domain knowledge on Flow and its internals. Making an archetype can be done "by anyone" as there is nothing specific to Flow about it (except the generated project). Historically the framework team has made the archetypes as there was really nobody else in the RnD team. But at this point I'm strongly against dumping even more work to the team that has dwindling resources even as is.

Like Artur suggests, generating something based on SVC would make sense. But getting the archetype out first is faster by just creating it like the existing one. That can be done quite fast as community effort and setup to be released and updated together with the platform.

**Comment by tarekoraby** [comment]
Closed by #178 and #179.
